/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface BlogdansUser {
  created_at: Generated<Timestamp>;
  id: string;
  photo: string;
  updated_at: Generated<Timestamp>;
}

export interface Comment {
  approved_at: Timestamp | null;
  author_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  post_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PasswordResetLog {
  email: string;
  id: Generated<string>;
  sent_at: Generated<Timestamp>;
}

export interface Post {
  created_at: Generated<Timestamp>;
  id: string;
  updated_at: Generated<Timestamp>;
}

export interface Roles {
  role: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserRoles {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  blogdans_user: BlogdansUser;
  comment: Comment;
  password_reset_log: PasswordResetLog;
  post: Post;
  roles: Roles;
  session: Session;
  user: User;
  user_roles: UserRoles;
  verification: Verification;
}
