#!/usr/bin/env bash

person=$(git log -n1 --format='format:%aN' | awk '{print $1}')
commithash=$(git log -n1 --format='format:%H')
commiturl="https://github.com/skagedal/blog.skagedal.tech/commit/${commithash}"
commit="<${commiturl}|commit>"

if [[ "$1" == "success" ]]; then
  msg="Deployed blogdans from ${person}'s latest ${commit}."
else
  msg="Failed to deploy blogdans from ${person}'s latest ${commit}."
fi

curl -X POST -H 'Content-type: application/json' \
  --data "{\"text\":\"$msg\"}" \
  "${SLACK_WEBHOOK_URL}"
