{
  name: "Build and push Docker image",
  on: { 
    push: { 
      branches: ["main"] 
    } 
  },
  jobs:
    {
      main:
        {
          name: "Build and deploy",
          "runs-on": "ubuntu-latest",
          steps:
            [
              { name: "Check out code", uses: "actions/checkout@v4" },
              {
                name: "Set up Docker Buildx",
                uses: "docker/setup-buildx-action@v3",
              },
              {
                name: "Log in to Docker Hub",
                uses: "docker/login-action@v3",
                with:
                  {
                    username: "${{ secrets.DOCKERHUB_USERNAME }}",
                    password: "${{ secrets.DOCKERHUB_TOKEN }}",
                  },
              },
              { 
                id: "pnpm", 
                name: "Set up pnpm", 
                uses: "pnpm/action-setup@v4" 
              },
              {
                id: "node",
                name: "Set up Node.js",
                uses: "actions/setup-node@v4",
                with: { 
                  node-version-file: ".nvmrc", 
                  cache: "pnpm" 
                },
              },
              {
                name: "Install dependencies",
                run: "pnpm install --frozen-lockfile",
              },
              { 
                name: "Build Next.js app", 
                run: "pnpm run build" 
              },
              {
                name: "Build and push",
                uses: "docker/build-push-action@v5",
                with:
                  {
                    context: ".",
                    push: true,
                    tags: "skagedal/blogdans:latest",
                  },
              },
              {
                id: "ssh",
                name: "Set up SSH",
                env:
                  {
                    SSH_KEY: "${{ secrets.SSH_KEY }}",
                    SSH_KNOWN_HOSTS: "${{ secrets.SSH_KNOWN_HOSTS }}",
                  },
                run: "./ci/setup-ssh",
              },
              {
                name: "Deploy files to server",
                run: "rsync --archive --verbose --compress --delete ./bin ./db blogdans:",
              },
              {
                name: "Run migrations",
                run: "ssh blogdans ./bin/run-migrations"
              },
              {
                name: "Pull Docker image",
                run: "ssh blogdans ./bin/fetch-latest",
              },
              {
                name: "Stop Docker container, making systemd restart it",
                run: "ssh blogdans ./bin/stop-service",
              },
            ],
        },
    },
}
